### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by theepiccoder** [Electron-Games/Militery-Base#1]
Crash on startup.

Exception in thread "main" java.lang.ExceptionInInitializerError
    at com.thecherno.rain.entity.mob.Player.<init>(Player.java:45)
    at com.thecherno.rain.Game.<init>(Game.java:123)
    at com.thecherno.rain.Game.main(Game.java:290)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 3136
    at com.thecherno.rain.graphics.Sprite.load(Sprite.java:191)
    at com.thecherno.rain.graphics.Sprite.<init>(Sprite.java:132)
    at com.thecherno.rain.graphics.Sprite.<clinit>(Sprite.java:71)
    ... 3 more

**Comment by theepiccoder** [comment]
Fixed.
